apiVersion: v1
kind: Pod
metadata:
  name: ace-pod
  namespace: ace
  labels:
    app: ace-pod
spec:
  containers:
  - name: ace-server
    imagePullPolicy: Always
    image: tdolby/experimental:ace-configurable-12.0.7.0-1
    env:
    - name: 'LICENSE'
      value: 'accept'
    volumeMounts:
    - name: config-volume
      mountPath: /var/configmap
  volumes:
  - name: config-volume
    configMap:
      name: global-cache-setup
  restartPolicy: Never
